### ISSUE TITLE
Dennis' Social media is missing

### ISSUE THREAD

**Issue by sergiogval** [sumairq/morse-code#2]
# Hi guys

Just to let you know that on the readme Dennis' contact is missing.

Have a great day!

**Comment by sumairq** [comment]
Thank you Sergio. I implemented your feedback.

<img src="https://media1.giphy.com/media/F0J0uiNS8n0BHSQmDt/giphy.gif"/>

**Comment by sergiogval** [comment]
You are wellcome, kind regards!
